INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(11 ,"Cao Bằng");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(12 ,"Lạng Sơn");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(14 ,"Quảng Ninh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(15 ,"Hải Phòng");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(16 ,"Hải Phòng");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(17 ,"Thái Bình");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(18 ,"Nam Định");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(19 ,"Phú Thọ");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(20 ,"Thái Nguyên");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(21 ,"Yên Bái");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(22 ,"Tuyên Quang");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(23 ,"Hà Giang");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(24 ,"Lào Cai");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(25 ,"Lai Châu");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(26 ,"Sơn La");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(27 ,"Điện Biên");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(28 ,"Hòa Bình");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(29 ,"Hà Nội");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(30 ,"Hà Nội");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(31 ,"Hà Nội");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(32 ,"Hà Nội");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(33 ,"Hà Nội");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(34 ,"Hải Dương");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(35 ,"Ninh Bình");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(36 ,"Thanh Hóa");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(37 ,"Nghệ An");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(38 ,"Hà Tĩnh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(39 ,"Đồng Nai");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(40 ,"Hà Nội");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(41 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(43 ,"Đà Nẵng");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(47 ,"Đắk Lắk");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(48 ,"Đắk Nông");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(49 ,"Lâm Đồng");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(50 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(51 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(52 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(53 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(54 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(55 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(56 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(57 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(58 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(59 ,"TP.Hồ Chí Minh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(60 ,"Đồng Nai");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(61 ,"Bình Dương");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(62 ,"Long An");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(63 ,"Tiền Giang");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(64 ,"Vĩnh Long");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(65 ,"Cần Thơ");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(66 ,"Đồng Tháp");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(67 ,"An Giang");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(68 ,"Kiên Giang");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(69 ,"Cà Mau");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(70 ,"Tây Ninh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(71 ,"Bến Tre");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(72 ,"Bà Rịa - Vũng Tàu");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(73 ,"Quảng Bình");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(74 ,"Quảng Trị");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(75 ,"Thừa Thiên Huế");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(76 ,"Quảng Ngãi");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(77 ,"Bình Định");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(78 ,"Phú Yên");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(79 ,"Khánh Hòa");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(80 ,"Cục Cảnh sát giao thông");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(81 ,"Gia Lai");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(82 ,"Kon Tum");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(83 ,"Sóc Trăng");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(84 ,"Trà Vinh");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(85 ,"Ninh Thuận");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(86 ,"Bình Thuận");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(88 ,"Vĩnh Phúc");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(89 ,"Hưng Yên");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(90 ,"Hà Nam");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(92 ,"Quảng Nam");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(93 ,"Bình Phước");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(94 ,"Bạc Liêu");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(95 ,"Hậu Giang");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(97 ,"Bắc Cạn");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(98 ,"Bắc Giang");
INSERT INTO tinhthanh(STT,TenTinhThanh) VALUES(99 ,"Bắc Ninh");