CREATE TABLE TrangThaibauCu(
	GhiNhan VARCHAR(1) DEFAULT "0",
	ID_CuTri VARCHAR(14),ID_DonViBauCu SMALLINT,
	ngayBD DATETIME,
	FOREIGN KEY(ID_DonViBauCu) REFERENCES DonViBauCu(ID_DonViBauCu),
	FOREIGN KEY(ID_CuTri) REFERENCES CuTri(ID_CuTri),
	FOREIGN KEY(ngayBD) REFERENCES kybaucu(ngayBD) 
);