CREATE TABLE ChiTietBauCu(
	ThoiDiemBatBau DATETIME,
	BinhChon VARCHAR(1) DEFAULT "0",
	ID_Phieu VARCHAR(18),
	ID_ucv VARCHAR(14),
	ID_CuTri VARCHAR(14),
	FOREIGN KEY(ID_CuTri) REFERENCES CuTri(ID_CuTri),
	FOREIGN KEY(ID_ucv) REFERENCES UngCuVien(ID_ucv),
	FOREIGN KEY(ID_Phieu) REFERENCES PhieuBau(ID_Phieu) 
);