CREATE TABLE TaiKhoan(
	TaiKhoan VARCHAR(30) PRIMARY KEY,
	MatKhau VARCHAR(100) NOT NULL,
	BiKhoa VARCHAR(1),
	LyDoKhoa VARCHAR(100),
	NgayTao DATE,
	SuDung TINYINT,
	RoleID TINYINT NOT null,
	FOREIGN KEY(RoleID) REFERENCES VaiTro(RoleID)
);