CREATE TABLE DiaChiTamTru(
	ID_ucv VARCHAR(14),
	ID_CuTri VARCHAR(14),
	ID_QH INT,
	FOREIGN KEY(ID_CuTri) REFERENCES CuTri(ID_CuTri),
	FOREIGN KEY(ID_ucv) REFERENCES UngCuVien(ID_ucv),
	FOREIGN KEY(ID_QH) REFERENCES quanhuyen(ID_QH)
);